name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Login Hub
      env:
        TOKEN: ${{ secrets.HUB_TOKEN }}
      run: docker login -u globalinfra --password "$TOKEN"
    - name: Build the master Docker image
      run: docker build -t "globalinfra/runner:latest" . 
      if: endsWith(github.ref, 'refs/heads/master')
    - name: Push the master Docker image
      run: docker push "globalinfra/runner:latest"
      if: endssWith(github.ref, 'refs/heads/master')
    - name: Build the Tag Docker image
      run: docker build -t "globalinfra/runner:$GITHUB_REF_NAME" .
      if: startsWith(github.ref_name, 'refs/tags/v')
    - name: Push the Tag Docker image
      run: docker push "globalinfra/runner:$GITHUB_REF_NAME"
      if: startsWith(github.ref_name, 'refs/tags/v')