name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Login Hub
      env:
        TOKEN: ${{ secrets.HUB_TOKEN }}
      run: docker login -u globalinfra --password "$TOKEN"
    - name: Build the Docker image
      run: docker build -t "globalinfra/runner:latest" .
      if: startsWith(github.ref, 'refs/heads/master')
    - name: Push the Docker image
      run: docker push "globalinfra/runner:$GITHUB_REF_NAME"